name: Deploy [Production]

on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: Deploy

    runs-on: ubuntu-latest

    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v3

      - name: 📍 Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'

      - name: 🌩️ Run install
        uses: borales/actions-yarn@v4
        with:
          cmd: install # will run `yarn install` command

      - name: 🔨 Build Project
        uses: borales/actions-yarn@v4
        env:
          VITE_APP_BASE_URL: ${{ vars.API_PROD_BASE_URL }}
        with:
          cmd: build # will run `yarn build` command

      - name: 🚒 Install SSH Key
        uses: benoitchantre/setup-ssh-authentication-action@1.0.0
        with:
          private-key: ${{ secrets.SSH_PROD_PRIVATE_KEY }}

      - name: 🧸 Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.SSH_PROD_HOST }} >> ~/.ssh/known_hosts

      - name: 🚀 Deploy with rsync
        run: rsync -avz ./dist/ ${{ secrets.SSH_PROD_USER }}@${{ secrets.SSH_PROD_HOST }}:/var/www/ksbtech-admin/
